# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Cash Weaver"
description:        "a blog"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "//cashweaver.com"
author:             "cbweaver"
twitter:
  username:         "cashweaver"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "//cashweaver.com/about"
  - name:           "GitHub"
    href:           "//github.com/cbweaver"
  - name:           "Twitter"
    href:           "//twitter.com/cashweaver"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-seo-tag
